CREATE TABLE "M2_DEPARTMENT"
(							"DEPT_ID_PK" 				NUMBER 						PRIMARY KEY,
							"DEPT_NAME"					VARCHAR2(400) 				NOT NULL,
							"LOCATION" 					VARCHAR2(400) 				NOT NULL,
							"NUM_EMP" 					NUMBER 						NOT NULL
);
/

INSERT INTO "M2_DEPARTMENT"
(DEPT_ID_PK, DEPT_NAME, LOCATION, NUM_EMP)
VALUES
(874901, "INFORMATION TECHNOLOGY AND HUMAN RESOURCES", "NO WHERE, USA", 65);




CREATE TABLE "M2_INSURANCE"
(							"COMP_ID_PK" 				NUMBER 						PRIMARY KEY,
							"COMP_NAME" 				VARCHAR2(400) 				NOT NULL,
							"COVERAGE" 					VARCHAR2(400)				 
							"LOCATION" 					VARCHAR2(400) 				NOT NULL
);
/

INSERT INTO "M2_INSURANCE"
	(COMP_ID_PK, COMP_NAME, COVERAGE, LOCATION)
VALUES
	(50, "EXPENSIVE INSURANCE", "FAMILY", "SOMEWHERE, USA");

INSERT INTO "M2_INSURANCE"
	(COMP_ID_PK, COMP_NAME, COVERAGE, LOCATION)
VALUES
	(35, "LONELY INSURANCE", "SINGLE", "SOMEWHERE, USA");

INSERT INTO "M2_INSURANCE"
	(COMP_ID_PK, COMP_NAME, COVERAGE, LOCATION)
VALUES
	(62, "FAILURE INSURANCE", NULL, "SOMEWHERE, USA");

DELETE FROM "M2_INSURANCE"																								
WHERE COMP_ID_PK = 50;

COMMIT;


CREATE TABLE "M2_EMPLOYEE"
(							"EMP_ID_PK" 				NUMBER 						PRIMARY KEY,
							"FNAME" 					VARCHAR2(400) 				NOT NULL,
							"LNAME" 					VARCHAR2(400) 				NOT NULL,
							"POSITION" 					VARCHAR2(400) 				NOT NULL,
							"SALARY" 					NUMBER 						NOT NULL

CONSTRAINT DEPT_ID_FK FOREIGN KEY (DEPT_ID_PK) REFERENCES M2_DEPARTMENT (DEPT_ID_PK)
);
/

INSERT INTO "M2_EMPLOYEE"
	(EMP_ID_PK, FNAME, LNAME, POSITION, SALARY)
VALUES
	(1, "CAVE", "JOHNSON", "APERTURE SCIENCE CEO", 500);

INSERT INTO "M2_EMPLOYEE"
	(EMP_ID_PK, FNAME, LNAME, POSITION, SALARY)
VALUES
	(2, "CAROLYN", "UNKNOWN", "APERTURE SCIENCE ASSISTANT", 250);

INSERT INTO "M2_EMPLOYEE"
	(EMP_ID_PK, FNAME, LNAME, POSITION, SALARY)
VALUES
	(3, "MISTER", "WHEATLEY", "APERTURE SCIENCE IDIOT", 1);

INSERT INTO "M2_EMPLOYEE"
	(EMP_ID_PK, FNAME, LNAME, POSITION, SALARY)
VALUES
	(4, "LAB", "BOY", "APERTURE SCIENCE SCIENTIST", 150);

INSERT INTO "M2_EMPLOYEE"
	(EMP_ID_PK, FNAME, LNAME, POSITION, SALARY)
VALUES
	(5, "HOMELESS", "MAN", "APERTURE SCIENCE TESTER", 1);

DELETE FROM "M2_EMPLOYEE" 																						
WHERE LNAME = "WHEATLEY";

COMMIT;

--> I know these aren't right
ALTER TABLE "M2_EMPLOYEE"									
MODIFY "M2_EMPLOYEE" 																					
WHERE FNAME = "HOMELESS"
TO FNAME = "VOLUNTEER";

ALTER TABLE "M2_EMPLOYEE"
MODIFY "M2_EMPLOYEE" 																						
WHERE SALARY = 1
TO SALARY = 0;
-->

COMMIT;

SELECT *
FROM "M2_EMPLOYEE"
WHERE POSITION = "APERTURE SCIENCE CEO";

SELECT *
FROM "M2_EMPLOYEE"
WHERE DEPT_ID_FK = 874901
ORDER BY LNAME DESC;




CREATE TABLE "M2_DEP_INS"
(							"DEP_ID_PK" 				NUMBER 						PRIMARY KEY,
							"FNAME" 					VARCHAR2(400) 				NOT NULL,
							"LNAME" 					VARCHAR2(400) 				NOT NULL,
							"RELATIONSHIP" 				VARCHAR2(400) 				NOT NULL,   

CONSTRAINT EMP_ID_FK FOREIGN KEY (EMP_ID_PK) REFERENCES M2_EMPLOYEE (EMP_ID_PK)
CONSTRAINT COMP_ID_FK FOREIGN KEY (COMP_ID_PK) REFERENCES M2_INSURANCE (COMP_ID_PK)
);
/




CREATE TABLE "M2_ACCOUNTS"
(							"ACCT_ID_PK" 				NUMBER 						PRIMARY KEY,
							"ACCT_NUM" 					NUMBER 						UNIQUE,
							"CURRENT_BAL" 				NUMBER 						NOT NULL

CONSTRAINT CLIENT_ID_FK FOREIGN KEY (CLIENT_ID_PK) REFERENCES M2_CLIENTS (CLIENT_ID_PK)
);
/




CREATE TABLE "M2_CLIENTS"
(							"CLIENT_ID_PK" 				NUMBER 						PRIMARY KEY,
							"FNAME" 					VARCHAR2(400) 				NOT NULL,
							"LNAME" 					VARCHAR2(400) 				NOT NULL,
							"TOTAL_BAL" 				NUMBER 						NOT NULL

CONSTRAINT ACCT_ID_FK FOREIGN KEY (ACCT_ID_PK) REFERENCES M2_ACCOUNTS (ACCT_ID_PK)
);
/

ALTER TABLE "M2_CLIENTS" ADD CONSTRAINT ACCT_CLIENT_FK FOREIGN KEY (ACCT_ID_PK) REFERENCES M2_ACCOUNTS (ACCT_ID_PK);
ALTER TABLE "M2_ACCOUNTS" ADD CONSTRAINT CLIENT_ACCT_FK FOREIGN KEY (CLIENT_ID_PK) REFERENCES M2_CLIENTS (CLIENT_ID_PK);




CREATE TABLE "M2_LOANS"
(							"LOAN_ID_PK" 				NUMBER 						PRIMARY KEY,
							"AMOUNT" 					NUMBER 						NOT NULL,
							"DURATION" 					NUMBER 						NOT NULL

CONSTRAINT CLIENT_ID_FK FOREIGN KEY (CLIENT_ID_PK) REFERENCES M2_CLIENTS (CLIENT_ID_PK)
CONSTRAINT EMP_ID_FK FOREIGN KEY (EMP_ID_PK) REFERENCES M2_EMPLOYEE (EMP_ID_PK)
);
/




CREATE TABLE "M2_TRANSACTIONS"
(							"TRANS_ID_PK" 				NUMBER 						PRIMARY KEY,
							"TRANS_DATE" 				DATE 						NOT NULL,
							"AMOUNT" 					NUMBER(10, 2) 				NOT NULL

CONSTRAINT CLIENT_ID_FK FOREIGN KEY (CLIENT_ID_PK) REFERENCES M2_CLIENTS (CLIENT_ID_PK)
CONSTRAINT ACCT_ID_FK FOREIGN KEY (ACCT_ID_PK) REFERENCES M2_ACCOUNTS (ACCT_ID_PK)
);
/




CREATE TABLE "M2_CHECK_DEPOSITS"
ADD CONSTRAINT CHK_RECIEVED_PROCESSED CHECK (DATE_PROCESSED > DATE_RECEIVED);
(							"CHECK_ID_PK" 				NUMBER 						PRIMARY KEY,
							"CHECK_NUM" 				NUMBER 						NOT NULL,
							"BANK_SOURCE" 				VARCHAR2(400) 				NOT NULL, 
							"DATE_RECEIVED" 			DATE 						NOT NULL,
							"DATE_PROCESSED" 			DATE 						NOT NULL

CONSTRAINT CLIENT_ID_FK FOREIGN KEY (CLIENT_ID_PK) REFERENCES M2_CLIENTS (CLIENT_ID_PK)
);
/
